name: keep awake

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSfL https://invest-screen.streamlit.app > /dev/null
      
